### ISSUE TITLE
Highlighting Reports

### ISSUE THREAD

**Issue by jblack4vols** [healthproai/healthproai#4]
highlighting specifics mentioned to Donald

**Comment by imgnx** [comment]
Data is anonymized.

![image](https://github.com/healthproai/healthproai/assets/20768148/1ea00ec3-5579-454b-af44-811080532062)

![image](https://github.com/healthproai/healthproai/assets/20768148/9ee981d1-43fc-47e3-851d-13a6c45a8bfd)

![image](https://github.com/healthproai/healthproai/assets/20768148/6e8c8535-b461-4e7b-9e93-f12b4613f321)
